kind: pipeline
type: docker
name: default

steps:
- name: build
  image: konttipoju/tinytex:2020-04a
  commands:
  - apt-get update && apt-get -y install make fonts-linuxlibertine
  - tlmgr update --self
  - tlmgr install fontawesome5 textpos titlesec graphbox xhfill smartdiagram hyphen-russian
  - make

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: RELEASE_TOKEN
    files: "*.pdf"
  when:
    event: tag
